export const PRODUCT_LIST_PENDDING = 'PRODUCT_LIST_PENDDING';
export const PRODUCT_LIST_SUCCESSED = 'PRODUCT_LIST_SUCCESSED';
export const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED';

export const PRODUCT_DETAILS_PENDDING = 'PRODUCT_LIST_PENDDING';
export const PRODUCT_DETAILS_SUCCESSED = 'PRODUCT_LIST_SUCCESSED';
export const PRODUCT_DETAILS_FAILED = 'PRODUCT_LIST_FAILED';